# Generated by Django 2.1 on 2018-08-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectname', models.CharField(max_length=140)),
                ('date_added', models.DateTimeField(verbose_name='Date Published')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
