# Generated by Django 2.1 on 2018-09-11 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randobject',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
